ALTER TABLE autore ALTER COLUMN id SET DEFAULT nextval('autore_seq');
ALTER TABLE libro ALTER COLUMN id SET DEFAULT nextval('libro_seq');

INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('George', 'Orwell', '1903-06-25', '1950-01-21', 'GBR', 1);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Haruki', 'Murakami', '1949-01-12', NULL, 'JPN', 2);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Jane', 'Austen', '1775-12-16', '1817-07-18', 'GBR', 3);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Fyodor', 'Dostoevsky', '1821-11-11', '1881-02-09', 'RUS', 4);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Joanne Kathleen', 'Rowling', '1965-07-31', NULL, 'GBR', 5);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Gabriel', 'García Márquez', '1927-03-06', '2014-04-17', 'COL', 6);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Stephen', 'King', '1947-09-21', NULL, 'USA', 7);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Margaret', 'Atwood', '1939-11-18', NULL, 'CAN', 8);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Umberto', 'Eco', '1932-01-05', '2016-02-19', 'ITA', 9);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Chimamanda Ngozi', 'Adichie', '1977-09-15', NULL, 'NGA', 10);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Lev', 'Tolstoy', '1828-09-09', '1910-11-20', 'RUS', 11);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Franz', 'Kafka', '1883-07-03', '1924-06-03', 'CZE', 12);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Italo', 'Calvino', '1923-10-15', '1985-09-19', 'ITA', 13);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Isabel', 'Allende', '1942-08-02', NULL, 'CHL', 14);
INSERT INTO autore(first_name, last_name, date_of_birth, date_of_death, nationality, immagine_id) VALUES ('Albert', 'Camus', '1913-11-07', '1960-01-04', 'FRA', 15);

INSERT INTO libro(title, year) VALUES ('1984', 1949);
INSERT INTO libro(title, year) VALUES ('Animal Farm', 1945);
INSERT INTO libro(title, year) VALUES ('Norwegian Wood', 1987);
INSERT INTO libro(title, year) VALUES ('Kafka on the Shore', 2002);
INSERT INTO libro(title, year) VALUES ('Pride and Prejudice', 1813);
INSERT INTO libro(title, year) VALUES ('Emma', 1815);
INSERT INTO libro(title, year) VALUES ('Crime and Punishment', 1866);
INSERT INTO libro(title, year) VALUES ('The Brothers Karamazov', 1880);
INSERT INTO libro(title, year) VALUES ('Harry Potter and the Philosopher''s Stone', 1997);
INSERT INTO libro(title, year) VALUES ('Harry Potter and the Chamber of Secrets', 1998);
INSERT INTO libro(title, year) VALUES ('One Hundred Years of Solitude', 1967);
INSERT INTO libro(title, year) VALUES ('Love in the Time of Cholera', 1985);
INSERT INTO libro(title, year) VALUES ('The Shining', 1977);
INSERT INTO libro(title, year) VALUES ('It', 1986);
INSERT INTO libro(title, year) VALUES ('The Handmaid''s Tale', 1985);
INSERT INTO libro(title, year) VALUES ('Oryx and Crake', 2003);
INSERT INTO libro(title, year) VALUES ('The Name of the Rose', 1980);
INSERT INTO libro(title, year) VALUES ('Foucault''s Pendulum', 1988);
INSERT INTO libro(title, year) VALUES ('Americanah', 2013);
INSERT INTO libro(title, year) VALUES ('War and Peace', 1869);
INSERT INTO libro(title, year) VALUES ('Anna Karenina', 1877);
INSERT INTO libro(title, year) VALUES ('The Trial', 1925);
INSERT INTO libro(title, year) VALUES ('The Metamorphosis', 1915);
INSERT INTO libro(title, year) VALUES ('Invisible Cities', 1972);
INSERT INTO libro(title, year) VALUES ('If on a winter''s night a traveler', 1979);
INSERT INTO libro(title, year) VALUES ('The House of the Spirits', 1982);
INSERT INTO libro(title, year) VALUES ('The Stranger', 1942);
INSERT INTO libro(title, year) VALUES ('The Plague', 1947);
INSERT INTO libro(title, year) VALUES ('The Fall', 1956);
INSERT INTO libro(title, year) VALUES ('The Myth of Sisyphus', 1942);

INSERT INTO users(id, nickname, email) VALUES(nextval('users_seq'), 'Baolo', 'baolo@gmail.com');
INSERT INTO credentials(id, password, role, username, user_id) VALUES(nextval('credentials_seq'), '$2a$10$F605H0XOC06ODyI.oQnCzeMWpWRPNOH2DM2Lmf.ZSAkNrTG6Kqa3q', 'DEFAULT', 'baolo',currval('users_seq'));
INSERT INTO users(id, nickname, email) VALUES(nextval('users_seq'), 'Capo Supremo', 'admin@admin.com');
INSERT INTO credentials(id, password, role, username, user_id) VALUES(nextval('credentials_seq'), '$2a$12$Lzmhtr/JjTVh8zJF.6h6IOswJfrt.zmuS3yjvjZW999TJdDoRroQu', 'ADMIN', 'admin',currval('users_seq'));
INSERT INTO users(id, nickname, email) VALUES(nextval('users_seq'), 'Gabbo Matto','gab@gmail.com');
INSERT INTO credentials(id, password, role, username, user_id) VALUES(nextval('credentials_seq'), '$2a$12$PQe2m5BJW1AFWQPx0mNo0.RLn9ovbRE80FL/jBxQXK7g22bQmQ/XK', 'DEFAULT', 'gabbo',currval('users_seq'));
INSERT INTO users(id, nickname, email) VALUES(nextval('users_seq'), 'Michelino Piratino', 'mic@gmail.com');
INSERT INTO credentials(id, password, role, username, user_id) VALUES(nextval('credentials_seq'), '$2a$12$h1htYATmLrimpuKOSoJ2yep8Gdzbc0rnahtUM73/qJQB82kGXJCuW', 'DEFAULT', 'michelino',currval('users_seq'));

